// frontend/react/library-system/src/pages/Register/index.tsx
import { ArrowLeft } from "phosphor-react";
import { useNavigate } from "react-router-dom";

import openBookImage from "../../assets/open-book.png";
import librarianImage from "../../assets/librarian.png";
import bannerImage from "../../assets/footer-img2.png";

const Register = () => {
  const navigate = useNavigate();

  return (
    <div className=' flex justify-center items-center w-screen h-screen bg-white-container'>
      <div className='flex h-[90%] w-[70%] bg-white rounded-xl'>
        <div className='flex items-center justify-center h-full w-[70%]'>
          <div className='flex justify-evenly flex-col w-full h-full'>
            <div className='flex flex-col px-12 text-3xl font-semibold text-pink-300'>
              <ArrowLeft
                onClick={() => navigate("/login")}
                size={25}
                color='#fea6b5'
                className='mb-2 cursor-pointer font-semibold'
              />

              <span>Escolha um tipo de conta</span>
            </div>

            <div className='flex justify-center items-center h-3/5 w-full'>
              <div className='flex flex-col justify-evenly items-center w-2/5 h-3/5 m-2 rounded-3xl text-white text-2xl font-bold cursor-pointer bg-pink-400 transition-all hover:w-[45%] hover:h-[65%]'>
                <img
                  className='w-2/6'
                  src={openBookImage}
                  alt='Item Reader Choose Register'
                />
                <span>Leitor</span>
              </div>

              <div className='flex flex-col justify-evenly items-center w-2/5 h-3/5 m-2 rounded-3xl text-white text-2xl font-bold cursor-pointer bg-pink-300 transition-all hover:w-[45%] hover:h-[65%]'>
                <img
                  className='w-2/6'
                  src={librarianImage}
                  alt='Item Librarian Choose Register'
                />
                <span>Bibliotecário</span>
              </div>
            </div>
          </div>
        </div>

        <div className='flex items-center justify-center w-[30%] h-full rounded-2xl bg-pink-300'>
          <img
            src={bannerImage}
            className='w-[90%] cursor-pointer transition-all hover:w-[95%]'
          />
        </div>
      </div>
    </div>
  );
};

export default Register;

// frontend/vue/library-system/src/pages/Register/Register.vue
<template>
  <div class="body-container">
    <div class="box-container" style="height: 90%">
      <div class="box-info-container">
        <div class="box-choose-register" v-show="type === 'initial'">
          <ArrowLeftIcon size="25" class="icon-back" @click="backToLogin" />
          <span class="title-box-choose">Escolha um tipo de conta</span>
          <div class="items-register-choose">
            <div
              class="item-choose-register"
              style="background: #f9b5ac"
              @click="chooseType('reader')"
            >
              <img
                src="../../assets/open-book.png"
                alt="Item Reader Choose Register "
              />
              <span>Leitor</span>
            </div>
            <div
              class="item-choose-register"
              style="background: #ffb8d1"
              @click="chooseType('librarian')"
            >
              <img
                src="../../assets/librarian.png"
                alt="Item Librarian Choose Register"
              />
              <span>Bibliotecário</span>
            </div>
          </div>
        </div>

        <FormReaderRegister
          v-show="type === 'reader'"
          @chooseType="chooseType"
        />
        <FormLibrarianRegister
          v-show="type === 'librarian'"
          @chooseType="chooseType"
        />
      </div>
      <div class="box-banner">
        <img src="../../assets/footer-img2.png" alt="Register Image" />
      </div>
    </div>
  </div>
</template>

<script>
import FormReaderRegister from "@/components/Register/FormReaderRegister/FormReaderRegister.vue";
import FormLibrarianRegister from "@/components/Register/FormLibrarianRegister/FormLibrarianRegister.vue";
import { ArrowLeftIcon } from "vue-feather-icons";

export default {
  name: "RegisterPage",
  components: {
    // eslint-disable-next-line vue/no-unused-components
    FormReaderRegister,
    FormLibrarianRegister,
    ArrowLeftIcon,
  },
  data() {
    return {
      type: "initial",
    };
  },
  methods: {
    // eslint-disable-next-line no-unused-vars
    chooseType(typeRegister) {
      this.type = typeRegister;
    },
    backToLogin() {
      this.$router.push("/login");
    },
  },
};
</script>

<style scoped>
.box-choose-register {
  display: flex;
  justify-content: space-evenly;
  flex-direction: column;

  height: 100%;
  width: 100%;
}

.title-box-choose {
  padding: 0 50px;

  font-size: 30px;
  font-weight: 600;

  color: #fea6b5;
}

.items-register-choose {
  display: flex;
  justify-content: center;
  align-items: center;

  height: 60%;
  width: 100%;
}

.item-choose-register {
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;

  width: 40%;
  height: 60%;

  margin: 10px;

  border-radius: 20px;

  color: white;
  font-size: 25px;
  font-weight: 700;

  cursor: pointer;

  transition: all 0.3s;
}

.item-choose-register:hover {
  width: 45%;
  height: 65%;
}

.item-choose-register img {
  width: 30%;
}

@import "../../styles/global.css";

@import "../../pages/Login/style.css";
</style>
