// frontend/vue/library-system/src/components/Profile/General/General.vue
<template>
  <div>
    <h2 class="title-container" style="font-size: 25px">Meu perfil</h2>
    <p class="subtitle-container">Altere suas informações e troque de foto</p>
    <div class="infos-profile-container">
      <p class="subtitle-container" style="font-size: 18px; margin-bottom: 5px">
        Troque sua foto de perfil
      </p>
      <div class="section-image-profile">
        <div class="box-change-image" style="width: 55%">
          <img
            class="box-change-icon"
            src="../../../assets/user-icon-image.png"
            alt="Profile Image Change"
          />
          <div class="container-buttons-change-image">
            <button style="background: #fea6b5">Trocar de Foto</button>
            <button style="background: #e84393">Excluir Foto</button>
          </div>
        </div>
      </div>
      <p class="subtitle-container" style="font-size: 18px; margin-bottom: 5px">
        Atualize suas informações
      </p>
      <div
        class="box-info"
        style="height: 90%; width: 90%; margin-bottom: 20px"
      >
        <div class="input-container">
          <input class="input-submit" type="text" placeholder="Nome Completo" />
          <input class="input-submit" type="email" placeholder="Email" />
        </div>
        <div class="input-container">
          <input class="input-submit" type="text" placeholder="Identificação" />
          <input
            class="input-submit"
            v-mask="'##.###.###-#'"
            type="text"
            placeholder="RG"
          />
        </div>
        <div class="input-container">
          <input
            class="input-submit"
            v-mask="'###.###.###-##'"
            type="text"
            placeholder="CPF"
          />
          <input class="input-submit" type="password" placeholder="Senha" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ProfileComponent",
};
</script>

<style scoped>
.infos-profile-container {
  height: 80%;
}

.section-image-profile {
  display: flex;

  width: 100%;
  height: 200px;

  margin-bottom: 10px;
}

.box-change-image {
  display: flex;
  align-items: center;

  height: 100%;
}

.box-change-icon {
  width: 25%;
}

.container-buttons-change-image {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  width: 50%;
}

.container-buttons-change-image button {
  width: 70%;

  padding: 10px;

  margin-bottom: 10px;

  font-weight: 600;
  color: white;

  border-radius: 5px;

  cursor: pointer;

  border: none;
  outline: none;
}

.input-submit {
  width: 40%;

  margin: 10px;
}
</style>

// frontend/react/library-system/src/components/Profile/General/index.tsx
import avatarImg from "../../../assets/user-icon-image.png";

export const GeneralProfile = () => {
  return (
    <div className='flex flex-col gap-2 w-3/4'>
      <span className='text-2xl text-pink-300 font-semibold'>Meu Perfil</span>

      <p className='text-zinc-400 font-medium'>Altere suas informações!</p>

      <div className='flex items-center gap-10 h-40 w-1/2 my-10'>
        <img
          className='w-2/6 cursor-pointer opacity-50 transition-all hover:opacity-100'
          src={avatarImg}
          alt='Avatar User'
        />

        <div className='flex flex-col gap-2'>
          <span className='text-3xl font-semibold text-pink-300'>
            Olá, Igor Silva
          </span>
          <p className='text-base text-zinc-400'>Troque sua foto de perfil</p>
        </div>
      </div>

      <p className='text-lg text-zinc-400'>Atualize seus dados</p>

      <div className='flex flex-col gap-2 w-full'>
        <div className='flex items-center gap-2 w-full h-24'>
          <div className='flex flex-col gap-2 h-20 w-2/5'>
            <label className='text-sm text-pink-300 font-medium'>
              Nome Completo
            </label>
            <input className='border border-zinc-300 p-3 rounded outline-none text-zinc-400' />
          </div>

          <div className='flex flex-col gap-2 h-20 w-2/5'>
            <label className='text-sm text-pink-300 font-medium'>E-mail</label>
            <input
              type='email'
              className='border border-zinc-300 p-3 rounded outline-none text-zinc-400'
            />
          </div>
        </div>

        <div className='flex items-center gap-2 w-full h-24'>
          <div className='flex flex-col gap-2 h-20 w-2/5'>
            <label className='text-sm text-pink-300 font-medium'>CPF</label>
            <input className='border border-zinc-300 p-3 rounded outline-none text-zinc-400' />
          </div>

          <div className='flex flex-col gap-2 h-20 w-2/5'>
            <label className='text-sm text-pink-300 font-medium'>RG</label>
            <input className='border border-zinc-300 p-3 rounded outline-none text-zinc-400' />
          </div>
        </div>

        <button className='w-2/5 p-3 rounded text-white font-semibold bg-pink-300 mt-3 cursor-pointer transition-colors hover:bg-pink-400'>
          Atualizar
        </button>
      </div>
    </div>
  );
};
