// frontend/vue/library-system/src/pages/Login/Login.vue
<template>
  <div class="body-container">
    <div class="box-container">
      <div class="box-info-container">
        <div class="box-info">
          <span>Slibrary</span>
          <p class="sub-title-login">Entrar na Conta</p>
          <input class="input-submit" type="text" placeholder="Email" />
          <input class="input-submit" type="text" placeholder="Senha" />
          <p class="sing-in-text" @click="handleRegisterPage">
            Não tem conta? Registre-se
          </p>
        </div>
      </div>
      <div class="box-banner">
        <img src="../../assets/login-img.png" alt="Login Image" />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "LoginPage",
  methods: {
    handleRegisterPage() {
      this.$router.push("/register");
    },
  },
};
</script>

<style scoped>
@import "../../styles/global.css";

@import "./style.css";
</style>

// frontend/react/library-system/src/pages/Login/index.js
import { ArrowLeft } from "react-feather";
import { useNavigate } from "react-router-dom";

import {
  ContainerBody,
  BoxContainer,
  BoxInfoContainer,
  ButtonSubmit,
  InputSubmit,
} from "../../styles/styles";

import { BoxBanner, BoxInfo, SubTitleLogin, SingInText } from "./style";

import loginImage from "../../assets/login-img.png";

const Home = () => {
  const navigate = useNavigate();

  return (
    <ContainerBody>
      <BoxContainer>
        <BoxInfoContainer>
          <BoxInfo>
            <ArrowLeft
              style={{ cursor: "pointer" }}
              size={25}
              color='#fea6b5'
              onClick={() => navigate("/")}
            />
            <span>Slibrary</span>
            <SubTitleLogin>Entrar na Conta</SubTitleLogin>
            <InputSubmit placeholder='Email' />
            <InputSubmit placeholder='Senha' />
            <ButtonSubmit>Entrar</ButtonSubmit>
            <SingInText onClick={() => navigate("/register")}>
              Não tem conta? Registre-se
            </SingInText>
          </BoxInfo>
        </BoxInfoContainer>
        <BoxBanner>
          <img src={loginImage} />
        </BoxBanner>
      </BoxContainer>
    </ContainerBody>
  );
};

export default Home;
