// frontend/vue/library-system/src/pages/Profile/Profile.vue
<template>
  <div>
    <NavBar />
    <div class="container-profile">
      <div class="menu-options-profile">
        <p class="title-container">Pessoal</p>
        <div class="box-menu-items">
          <p class="menu-item">Geral</p>
          <p class="menu-item">Meus Livros</p>
          <p class="menu-item">Meus Emprestimos</p>
        </div>
        <p class="title-container">Livros</p>
        <div class="box-menu-items">
          <p class="menu-item">Criar Novo Livro</p>
          <p class="menu-item">Editar Livro & Deletar</p>
        </div>
      </div>
      <div class="section-profile">
        <Profile />
      </div>
    </div>
  </div>
</template>

<script>
import NavBar from "@/components/Navbar/NavBar.vue";
import Profile from "@/components/Profile/General/Profile.vue";

export default {
  name: "ProfilePage",
  components: {
    NavBar,
    Profile,
  },
};
</script>

<style>
.container-profile {
  display: flex;
  align-items: flex-start;

  width: 95vw;
  height: 100%;

  margin: 20px 0;
}

.menu-options-profile {
  display: flex;
  flex-direction: column;

  height: 400px;
  width: 20%;
}

.title-container {
  color: #fea6b5;

  font-size: 20px;
  font-weight: bold;

  margin-right: 10px;
  margin-bottom: 5px;
}

.box-menu-items {
  display: flex;
  flex-direction: column;

  width: 90%;

  margin: 0 10px 30px 5px;
}

.menu-item {
  font-size: 13px;
  font-weight: 500;

  color: #a3a3a1;

  cursor: pointer;

  padding: 5px;

  transition: color 0.3s;
}

.menu-item:hover {
  color: #fea6b5;
}

.section-profile {
  width: 80%;
}

.subtitle-container {
  font-size: 16px;
  font-weight: 400;

  color: #a3a3a1;

  margin-bottom: 50px;
}
</style>

// frontend/react/library-system/src/pages/Profile/index.tsx
import { NavBar } from "../../components/NavBar";
import { GeneralProfile } from "../../components/Profile/General";

const Profile = () => {
  return (
    <>
      <NavBar isSearch={false} />

      <div className='flex items-start w-[95vw] my-5'>
        <div className='flex flex-col gap-3 w-1/4'>
          <span className='text-xl text-pink-400 font-semibold'>Pessoal</span>

          <section className='w-full flex flex-col gap-2 h-16 mx-2 mb-2'>
            <p className='text-sm text-zinc-400 font-semibold cursor-pointer transition-colors hover:text-pink-300'>
              Geral
            </p>
            <p className='text-sm text-zinc-400 font-semibold cursor-pointer transition-colors hover:text-pink-300'>
              Todos Emprestimos Realizados
            </p>
          </section>

          <span className='text-xl text-pink-400 font-semibold'>Livros</span>

          <section className='w-full flex flex-col gap-2 h-16 mx-2'>
            <p className='text-sm text-zinc-400 font-semibold cursor-pointer transition-colors hover:text-pink-300'>
              Criar Novo Livro
            </p>
            <p className='text-sm text-zinc-400 font-semibold cursor-pointer transition-colors hover:text-pink-300'>
              Editar & Deletar Livro
            </p>
          </section>
        </div>

        <GeneralProfile />
      </div>
    </>
  );
};

export default Profile;
