// frontend/vue/library-system/src/pages/Register/Register.vue
<template>
  <div>
    <div class="body-container">
      <div class="box-container" style="height: 90%">
        <div class="box-info-container">
          <div class="box-info" style="height: 90%">
            <span style="fontsize: 25px">Crie sua conta</span>
            <input
              class="input-submit"
              type="text"
              placeholder="Nome Completo"
            />
            <input class="input-submit" type="text" placeholder="Email" />
            <input class="input-submit" type="text" placeholder="CPF" />
            <input class="input-submit" type="text" placeholder="RG" />
            <input class="input-submit" type="password" placeholder="Senha" />
            <button class="button-submit">Enviar</button>
          </div>
        </div>
        <div class="box-banner">
          <img src="../../assets/footer-img2.png" alt="Register Image" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "RegisterPage",
};
</script>

<style scoped>
@import "../../styles/global.css";
@import "../Login/style.css";
</style>

// frontend/react/library-system/src/pages/Register/index.js
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "react-feather";

import {
  ContainerBody,
  BoxContainer,
  BoxInfoContainer,
  ButtonSubmit,
  InputSubmit,
} from "../../styles/styles";

import { BoxBanner, BoxInfo } from "../Login/style";

import registerImage from "../../assets/footer-img2.png";

const Register = () => {
  const navigate = useNavigate();

  return (
    <ContainerBody>
      <BoxContainer style={{ height: "90%" }}>
        <BoxInfoContainer>
          <BoxInfo style={{ height: "90%" }}>
            <ArrowLeft
              style={{ cursor: "pointer" }}
              size={25}
              color='#fea6b5'
              onClick={() => navigate("/login")}
            />
            <span style={{ fontSize: "25px" }}>Crie sua conta</span>
            <InputSubmit placeholder='Nome Completo' />
            <InputSubmit placeholder='Email' />
            <InputSubmit placeholder='CPF' />
            <InputSubmit placeholder='RG' />
            <InputSubmit placeholder='Senha' />
            <ButtonSubmit>Enviar</ButtonSubmit>
          </BoxInfo>
        </BoxInfoContainer>
        <BoxBanner>
          <img src={registerImage} />
        </BoxBanner>
      </BoxContainer>
    </ContainerBody>
  );
};

export default Register;
