// frontend/react/library-system/src/components/NavBar/index.tsx
import classNames from "classnames";
import { Link, useNavigate } from "react-router-dom";

import { InputSearch } from "../InputSearch";

import logo from "../../assets/book-logo.png";
import userIcon from "../../assets/user.png";
import logoutIcon from "../../assets/logout.png";
import bagIcon from "../../assets/shopping-cart.png";

interface INavBar {
  isSearch: boolean;
  onClickBag?: () => void;
}

const NavBar = ({ isSearch, onClickBag }: INavBar) => {
  const navigate = useNavigate();

  return (
    <div
      className={classNames(
        "flex justify-start items-center w-[95vw] h-[80px]",
        {
          "border-y border-gray-300": isSearch,
        }
      )}
    >
      <div
        className={classNames("flex items-center", {
          "w-[40%]": isSearch,
          "w-[30%]": !isSearch,
        })}
      >
        <img className='w-[50px] cursor-pointer' src={logo} />
        <span className='text-xl font-semibold mx-2 text-gray-400'>
          Slibrary
        </span>
      </div>
      {isSearch ? (
        <>
          <InputSearch widthContainer='50%' />

          <div className='flex items-center w-[10%] h-1/2'>
            <img
              className='w-4 m-2 cursor-pointer'
              src={userIcon}
              onClick={() => navigate("/login")}
            />
            <img
              onClick={onClickBag}
              className='w-4 m-2 cursor-pointer'
              src={bagIcon}
            />
            <img className='w-4 m-2 cursor-pointer' src={logoutIcon} />
          </div>
        </>
      ) : (
        <div className='flex justify-evenly items-center w-[70%]'>
          <a className='font-medium text-gray-400 decoration-0 cursor-pointer p-1 hover:text-pink-300 transition-colors'>
            Inicio
          </a>
          <a className='font-medium text-gray-400 decoration-0 cursor-pointer p-1 hover:text-pink-300 transition-colors'>
            Explorar
          </a>
          <a className='font-medium text-gray-400 decoration-0 cursor-pointer p-1 hover:text-pink-300 transition-colors'>
            Meu Perfil
          </a>
        </div>
      )}
    </div>
  );
};

export { NavBar };

// frontend/vue/library-system/src/components/Navbar/NavBar.vue
<template>
  <div
    class="nav-bar-container"
    :style="[
      { justifyContent: isSearch ? 'space-between' : 'flex-start' },
      { borderBottom: isSearch ? '1px solid #bdc3c7' : 'none' },
    ]"
  >
    <div class="logo-book" :style="[{ width: isSearch ? '40%' : '20%' }]">
      <img @click="handleHome" src="../../assets/book-logo.png" />
      <span>Slibrary</span>
    </div>
    <template v-if="isSearch">
      <InputSearch
        colorInput="#b9b9b7"
        widthContainer="50%"
        heightContainer="50%"
        backgroundContainer="transparent"
        widthImage="3%"
        justifyContainer="flex-start"
        alignItems="center"
        placeHolder="Pesquise um livro"
      />
      <div class="container-icons">
        <img src="../../assets/user.png" @click="handleProfilePage" />
        <img src="../../assets/bell.png" />
      </div>
    </template>
    <template v-else>
      <div class="options-menu">
        <router-link to="/">Inicio</router-link>
        <a>Sobre</a>
        <router-link to="/explore">Explorar</router-link>
        <a>Meus livros</a>
        <router-link to="/login">Meu Perfil</router-link>
      </div>
    </template>
  </div>
</template>

<script>
import InputSearch from "../InputSearch/InputSearch.vue";

export default {
  name: "NavBarComponent",
  components: {
    InputSearch,
  },
  props: {
    isSearch: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    handleHome() {
      this.$router.push("/");
    },
    handleProfilePage() {
      this.$router.push(`/profile`);
    },
  },
};
</script>

<style scoped>
.nav-bar-container {
  display: flex;
  align-items: center;
  justify-content: flex-start;

  width: 95vw;
  height: 80px;

  border-bottom: none;
}

.logo-book {
  display: flex;
  align-items: center;

  height: 100%;

  cursor: pointer;
}

.logo-book img {
  width: 50px;
}

.logo-book span {
  color: #a3a3a1;

  font-size: 20px;
  font-weight: 600;

  margin: 0px 10px;
}

.options-menu {
  display: flex;
  align-items: center;
  justify-content: space-evenly;

  width: 70%;
  height: 100%;
}

.options-menu a {
  font-weight: 500;

  color: #a3a3a1;

  text-decoration: none;

  cursor: pointer;

  padding: 5px;

  transition: all 0.3s;
}

.options-menu a:hover {
  border-radius: 5px;

  color: #fea6b5;

  background: #ffe0e4;
}

.container-icons {
  display: flex;
  align-items: center;

  width: 10%;
  height: 50%;
}

.container-icons img {
  width: 15px;

  margin: 10px;

  cursor: pointer;
}
</style>
